---
members:
  default_value:
  required: true
  value_type: array
name:
  default_value:
  required: true
  value_type: string
permission:
  default_value:
  required: true
  value_type: string
repos:
  default_value:
  required: true
  value_type: array
