---
aliases:
  default_value:
  required: false
  value_type: array
archive:
  default_value: true
  required: false
  value_type: boolean
domain_membership:
  default_value: false
  required: false
  value_type: boolean
members:
  default_value:
  required: true
  value_type: array
name:
  default_value:
  required: true
  value_type: string
private:
  default_value: false
  required: false
  value_type: boolean
