---
emails:
  default_value: []
  required: true
  value_type: array
external:
  default_value: false
  required: true
  value_type: boolean
github:
  default_value:
  required: true
  value_type: string
name:
  default_value:
  required: true
  value_type: string
public_key:
  default_value:
  required: true
  value_type: string
